name: cs774
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - pytorch
  - jupyterlab
  - ipywidgets
  - sentencepiece
  - pip
  - pip:
      - ollama
      - langchain
      - transformers
      - sentence-transformers
      - accelerate
